name: 'Sijil React Benchmark'
description: 'Runs Vitest benchmarks.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run React Benchmarks
      run: |
        TARGET_DIR=$(dirname $(find . -name "package.json" | head -n 1))
        if [ -n "$TARGET_DIR" ]; then cd "$TARGET_DIR" || exit 1; fi
        npm install
        npx vitest bench --run
      shell: bash
