name: 'Sijil Python Linter (Ruff)'
description: 'Runs Ruff for Python linting.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Ruff
      run: |
        pip install ruff
      shell: bash
    - name: Run Ruff
      run: |
        TARGET_DIR=$(dirname $(find . -name "pyproject.toml" | head -n 1))
        if [ -n "$TARGET_DIR" ]; then cd "$TARGET_DIR" || exit 1; fi
        ruff check .
      shell: bash