name: 'Sijil SQL Linter'
description: 'Runs SQLFluff for database queries.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install SQLFluff
      run: |
        pip install sqlfluff
      shell: bash
    - name: Run SQLFluff Lint
      run: |
        sqlfluff lint . --dialect postgres
      shell: bash