name: 'Sijil Go Linter'
description: 'Runs golangci-lint.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.26.1'
        cache: true
    - name: Run golangci-lint
      run: |
        ROOT_FILE=$(find . -name "go.mod" | head -n 1)
        if [ -n "$ROOT_FILE" ]; then cd "$(dirname "$ROOT_FILE")" || exit 1; fi
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        $(go env GOPATH)/bin/golangci-lint run --timeout 10m
      shell: bash
