name: 'Sijil Go Linter (golangci-lint)'
description: 'Runs golangci-lint for Go code.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.26.1'
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.59.0
        args: run --timeout 5m ./...